In [2]:
#Numpy : Numerical Python
#In Numpy we see about arrays 

import numpy as np

In [3]:
l = [1,2,3,4]

In [5]:
arr = np.array(l)

In [6]:
arr      #1D

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.array([[1,2], [3,4]])     #2D

array([[1, 2],
       [3, 4]])

In [10]:
np.asarray(l)

array([1, 2, 3, 4])

In [11]:
a = [2,3,4]

In [13]:
np.asanyarray(a)

array([2, 3, 4])

In [14]:
b = np.matrix(l)    #By default matrix is 2D

In [15]:
b       

matrix([[1, 2, 3, 4]])

In [16]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [17]:
a = np.array(l)

In [18]:
c = a

In [19]:
c

array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c[0]

1

In [22]:
c[0] = 100

In [23]:
c

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
d = np.copy(a)

In [26]:
d

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
a[1] = 400

In [29]:
a

array([100, 400,   3,   4])

In [30]:
d    #New Location pe copy bana tha therefore koi changes nahi aya h d me

array([100,   2,   3,   4])

In [31]:
np.fromfunction(lambda i, j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [44]:
iterable = (i*i for i in range(5))

In [45]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [46]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [47]:
np.fromstring('4,5', sep = ',')

array([4., 5.])

In [48]:
#Numpy - Data Types

In [49]:
l = [2, 3, 4, 5, 6]

In [53]:
arr1 = np.array(l)

In [54]:
arr1

array([2, 3, 4, 5, 6])

In [55]:
arr1.ndim

1

In [56]:
arr2 = np.array([[1,2,3,4], [2,3,4,5]])

In [57]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [58]:
arr2.ndim

2

In [59]:
arr1.size

5

In [60]:
arr2.size

8

In [61]:
arr1.shape

(5,)

In [62]:
arr2.shape    #2 rows, 4 col

(2, 4)

In [63]:
arr1.dtype

dtype('int64')

In [64]:
arr2.dtype

dtype('int64')

In [66]:
arr3 = np.array([(1.4, 45, 45), (23, 45, 66)])

In [67]:
arr3

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [68]:
arr3.dtype

dtype('float64')

In [69]:
list(range(5))   #Range always take integer value

[0, 1, 2, 3, 4]

In [70]:
list(range(0.1, 5))

TypeError: 'float' object cannot be interpreted as an integer

In [71]:
np.arange(2.3, 5.6)    #arange function can take float values

array([2.3, 3.3, 4.3, 5.3])

In [72]:
np.arange(2.3, 5.6, .3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [73]:
list(np.arange(2.3, 5.6, .3))  #array to list is also possible

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [74]:
np.linspace(1, 5, 10)    # 1 to 5 it will give 10 values

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [75]:
np.zeros(5)   #1D (1 square bracket)

array([0., 0., 0., 0., 0.])

In [76]:
np.zeros((3, 4))  #2D (2 square bracket) 3 rows, 4 col

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.zeros((3, 4, 2))   #3D (3 square bracket)  We have 4 cross 2 and 3 such kind of matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [3]:
np.zeros((3,4,2,3))     #4D  We have 2 cross 3, four such matrixes  

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [4]:
arr4 = np.zeros((3,4,2,3)) 

In [5]:
arr4.ndim

4

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
one = np.ones((2,3,2))

In [10]:
one

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [11]:
one + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [12]:
one * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [14]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [15]:
np.eye(4)   #Indentity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [18]:
np.logspace(2,5 , 10)     #It will give log value between 2 to 5 
                            #And it will give 10 values (between 2 to 5)
                            #By default base value is 10 but we can change 

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [19]:
np.logspace(2,5 , 10, base = 2) 

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [20]:
np.random.randn(3,4)    #It will create 3 cross 4 matrix and the data will be random

array([[ 1.04491977,  2.09028494, -0.83177628, -0.67204363],
       [ 0.23897063, -1.45268515,  0.67526361, -0.85396398],
       [ 0.54003567, -0.25030009, -0.0413252 , -0.66724648]])

In [21]:
arr = np.random.randn(3,4)    #In case of random.randn fun mean is 0 and Standard Dev is 1(Normal Distribution)

In [22]:
import pandas as pd

In [23]:
pd.DataFrame(arr)

0         1         2         3
0 -0.601628 -1.017460 -0.490750 -1.484115
1 -0.944845 -0.770053 -0.209418  0.882514
2 -0.429646 -0.723569 -0.550178 -1.078128

In [24]:
np.random.rand(3,4)      

array([[0.42783965, 0.02594052, 0.50533406, 0.31760328],
       [0.43985032, 0.74770935, 0.56057641, 0.5261859 ],
       [0.68202997, 0.8296265 , 0.29523426, 0.06650662]])

In [25]:
np.random.randint(1,110 , (3,4))   #It will generate random data between 1 to 110 (3 rows and 4 col)

array([[  4,  11,  80,  52],
       [ 79,  19,  84, 105],
       [ 59,  36,  44,  91]])

In [26]:
np.random.randint(1,110 , (300,400))

array([[ 95,  98,   8, ...,  30,   7,  11],
       [ 31,  57, 101, ...,  15,  21,  96],
       [ 60,  60,  87, ..., 109,  30, 102],
       ...,
       [ 45, 101,  73, ...,  13,  45,  76],
       [106,  41,  82, ...,   9,  17,  32],
       [ 54,  29,  87, ...,  71,  20,   8]])

In [27]:
pd.DataFrame(np.random.randint(1,110 , (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     62   57   24   73   50    8   29    2   59   53  ...   23   62   61   
1     70   62   61   75   83   93   13   93  104   68  ...   82   96   45   
2     59   16   78   52   26   11   43   37   39  109  ...    8   47  100   
3    108   32   50   58   18  100  103   48   73   11  ...   84   21    7   
4     51   51   15   80   78   78   50   19   38   23  ...   77   93   99   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  105   67   56   43   66   53   19  101   81   93  ...   91  107   89   
296  107    9   56   18  104   68   65   79   92   82  ...  109   90   52   
297   38  102   73    6  102    1    5    9   70   80  ...   36   72   16   
298   90  101   32   59   31    1   65   54   22  103  ...   41   62   36   
299   39   48   90   71   43  107   58   37   15   56  ...   75  105   69   

     393  394  395  396  397  398  399  
0     92   14   65  100   72   34   45  
1     58   32   41   74   72    6   31  
2    106   76    5   71   79   68  102  
3     61   85  102   20   66    2   87  
4      3   74   80   21  106    8   72  
..   ...  ...  ...  ...  ...  ...  ...  
295   45   76    7    9   90   55   97  
296  108   61   40  105   73   48   24  
297   40   72   55   53   51   44   64  
298  107   73    6   21   53   62    2  
299   92   73    3   10   63   68   22  

[300 rows x 400 columns]

In [28]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')

In [29]:
arr = np.random.rand(3,4)

In [30]:
arr

array([[0.12482966, 0.95432498, 0.8782666 , 0.70677807],
       [0.38084386, 0.0527954 , 0.51898532, 0.31567216],
       [0.80602804, 0.29771452, 0.55992451, 0.91431084]])

In [31]:
arr.reshape(6,2)

array([[0.12482966, 0.95432498],
       [0.8782666 , 0.70677807],
       [0.38084386, 0.0527954 ],
       [0.51898532, 0.31567216],
       [0.80602804, 0.29771452],
       [0.55992451, 0.91431084]])

In [32]:
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [33]:
arr.reshape(6,-1)

array([[0.12482966, 0.95432498],
       [0.8782666 , 0.70677807],
       [0.38084386, 0.0527954 ],
       [0.51898532, 0.31567216],
       [0.80602804, 0.29771452],
       [0.55992451, 0.91431084]])

In [34]:
arr.reshape(6,-437923749237)    #By default it will take 6 cross 2 because there are 12 elements

array([[0.12482966, 0.95432498],
       [0.8782666 , 0.70677807],
       [0.38084386, 0.0527954 ],
       [0.51898532, 0.31567216],
       [0.80602804, 0.29771452],
       [0.55992451, 0.91431084]])

In [35]:
arr1 = arr.reshape(6,-437923749237)

In [36]:
arr1

array([[0.12482966, 0.95432498],
       [0.8782666 , 0.70677807],
       [0.38084386, 0.0527954 ],
       [0.51898532, 0.31567216],
       [0.80602804, 0.29771452],
       [0.55992451, 0.91431084]])

In [38]:
arr1[0][0]

0.12482965815009306

In [39]:
arr1[2:5, 1]

array([0.0527954 , 0.31567216, 0.29771452])

In [40]:
arr = np.random.randint(1,100 , (5,5))

In [41]:
arr

array([[80, 54, 46, 10, 65],
       [86, 16, 91, 99, 73],
       [47, 65, 50, 31, 21],
       [ 7, 16, 53, 23, 72],
       [49, 51, 28, 22, 17]])

In [42]:
arr>50

array([[ True,  True, False, False,  True],
       [ True, False,  True,  True,  True],
       [False,  True, False, False, False],
       [False, False,  True, False,  True],
       [False,  True, False, False, False]])

In [43]:
arr[arr>50]

array([80, 54, 65, 86, 91, 99, 73, 65, 53, 72, 51])

In [44]:
arr

array([[80, 54, 46, 10, 65],
       [86, 16, 91, 99, 73],
       [47, 65, 50, 31, 21],
       [ 7, 16, 53, 23, 72],
       [49, 51, 28, 22, 17]])

In [45]:
arr[2:4, [1,2]]

array([[65, 50],
       [16, 53]])

In [46]:
arr[0][0] = 5000

In [47]:
arr

array([[5000,   54,   46,   10,   65],
       [  86,   16,   91,   99,   73],
       [  47,   65,   50,   31,   21],
       [   7,   16,   53,   23,   72],
       [  49,   51,   28,   22,   17]])

In [48]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [49]:
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [50]:
arr2

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [51]:
arr1 + arr2

array([[4, 3, 3],
       [4, 4, 3],
       [2, 3, 2]])

In [52]:
arr1 - arr2

array([[ 0,  1, -1],
       [ 0,  0,  1],
       [ 0,  1,  0]])

In [53]:
arr1/arr2

array([[1. , 2. , 0.5],
       [1. , 1. , 2. ],
       [1. , 2. , 1. ]])

In [54]:
arr1*arr2   #This is not matrix multiplication

array([[4, 2, 2],
       [4, 4, 2],
       [1, 2, 1]])

In [55]:
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [56]:
arr2

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [57]:
arr1@arr2    #This is matrix multiplication

array([[ 9,  7,  7],
       [10,  8,  8],
       [ 7,  6,  5]])

In [58]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [59]:
arr1 + 100

array([[102, 102, 101],
       [102, 102, 102],
       [101, 102, 101]])

In [60]:
arr1**2

array([[4, 4, 1],
       [4, 4, 4],
       [1, 4, 1]])

In [61]:
#Numpy - Broadcastion

In [62]:
arr = np.zeros((4,4))

In [63]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
row = np.array([1,2,3,4])

In [65]:
row

array([1, 2, 3, 4])

In [66]:
arr + row    #Row-wise Broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [67]:
row.T    #We can not transpose 1D array

array([1, 2, 3, 4])

In [68]:
col = np.array([[1,2,3,4]])

In [69]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [70]:
col.T + arr   #Col-wise Broadcasting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [71]:
col

array([[1, 2, 3, 4]])

In [72]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
arr1 = np.random.randint(1,4 , (3,4))

In [74]:
arr1

array([[3, 3, 1, 2],
       [1, 2, 2, 1],
       [1, 1, 3, 1]])

In [75]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.73205081, 1.        ]])

In [76]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  2.71828183,  7.3890561 ],
       [ 2.71828183,  7.3890561 ,  7.3890561 ,  2.71828183],
       [ 2.71828183,  2.71828183, 20.08553692,  2.71828183]])

In [77]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.        , 0.30103   ],
       [0.        , 0.30103   , 0.30103   , 0.        ],
       [0.        , 0.        , 0.47712125, 0.        ]])