Numpy Part 2

In [1]:
#Numpy : Array Manipulation

In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10 , (3,4))

In [5]:
arr

array([[9, 4, 2, 1],
       [2, 4, 5, 8],
       [5, 2, 8, 8]])

In [8]:
arr.reshape(6,2)

array([[9, 4],
       [2, 1],
       [2, 4],
       [5, 8],
       [5, 2],
       [8, 8]])

In [9]:
arr.reshape(2,6)

array([[9, 4, 2, 1, 2, 4],
       [5, 8, 5, 2, 8, 8]])

In [10]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [11]:
arr.reshape(6,-7)

array([[9, 4],
       [2, 1],
       [2, 4],
       [5, 8],
       [5, 2],
       [8, 8]])

In [12]:
arr.T

array([[9, 2, 5],
       [4, 4, 2],
       [2, 5, 8],
       [1, 8, 8]])

In [13]:
arr

array([[9, 4, 2, 1],
       [2, 4, 5, 8],
       [5, 2, 8, 8]])

In [14]:
arr.flatten()   #It will convert into 1D array

array([9, 4, 2, 1, 2, 4, 5, 8, 5, 2, 8, 8])

In [15]:
arr1 = np.array([1,2,3,3,4])

In [16]:
arr1.ndim   #It gives dimension of the array

1

In [ ]:
np.expand_dims(arr1, axis = 1)  #axis = 0 : row, axis = 1 : col

#It converts into 2D array across col because axis = 1

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [18]:
np.expand_dims(arr1, axis = 0)        #It converts into 2D array across col because axis = 1

array([[1, 2, 3, 3, 4]])

In [19]:
arr

array([[9, 4, 2, 1],
       [2, 4, 5, 8],
       [5, 2, 8, 8]])

In [20]:
np.squeeze(arr)

array([[9, 4, 2, 1],
       [2, 4, 5, 8],
       [5, 2, 8, 8]])

In [21]:
data = np.array([[1], [2], [3]])

In [22]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.squeeze(data)  #It converts into single dim array 

array([1, 2, 3])

In [24]:
arr1

array([1, 2, 3, 3, 4])

In [25]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [26]:
np.roll(arr1, 2)   #shift = 2

array([3, 4, 1, 2, 3])

In [27]:
arr1

array([1, 2, 3, 3, 4])

In [28]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [30]:
arr1 = np.random.randint(1,10 , (3,4))   #It generates data between 1 to 10 and the matrix will be 3 cross 4

In [31]:
arr2 = np.random.randint(1,10 , (3,4))

In [32]:
arr1

array([[1, 3, 8, 8],
       [4, 3, 5, 8],
       [7, 5, 5, 3]])

In [33]:
arr2

array([[5, 7, 7, 5],
       [2, 6, 2, 5],
       [3, 2, 8, 8]])

In [34]:
arr1 + arr2

array([[ 6, 10, 15, 13],
       [ 6,  9,  7, 13],
       [10,  7, 13, 11]])

In [35]:
arr1 * arr2

array([[ 5, 21, 56, 40],
       [ 8, 18, 10, 40],
       [21, 10, 40, 24]])

In [36]:
arr1/arr2

array([[0.2       , 0.42857143, 1.14285714, 1.6       ],
       [2.        , 0.5       , 2.5       , 1.6       ],
       [2.33333333, 2.5       , 0.625     , 0.375     ]])

In [37]:
arr1-arr2

array([[-4, -4,  1,  3],
       [ 2, -3,  3,  3],
       [ 4,  3, -3, -5]])

In [38]:
arr1%arr2

array([[1, 3, 1, 3],
       [0, 3, 1, 3],
       [1, 1, 5, 3]])

In [39]:
arr1 ** arr2

array([[      1,    2187, 2097152,   32768],
       [     16,     729,      25,   32768],
       [    343,      25,  390625,    6561]])

In [40]:
arr1 & arr2

array([[1, 3, 0, 0],
       [0, 2, 0, 0],
       [3, 0, 0, 0]])

In [41]:
arr1

array([[1, 3, 8, 8],
       [4, 3, 5, 8],
       [7, 5, 5, 3]])

In [42]:
arr2

array([[5, 7, 7, 5],
       [2, 6, 2, 5],
       [3, 2, 8, 8]])

In [44]:
~arr1   #Negation

array([[-2, -4, -9, -9],
       [-5, -4, -6, -9],
       [-8, -6, -6, -4]])

In [45]:
arr1 | arr2

array([[ 5,  7, 15, 13],
       [ 6,  7,  7, 13],
       [ 7,  7, 13, 11]])

In [46]:
arr1>arr2

array([[False, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False, False]])

In [52]:
#String Function

arr = np.array(['prince', 'choudhury'])

In [53]:
arr

array(['prince', 'choudhury'], dtype='<U9')

In [54]:
np.char.upper(arr)

array(['PRINCE', 'CHOUDHURY'], dtype='<U9')

In [55]:
np.char.title(arr)

array(['Prince', 'Choudhury'], dtype='<U9')

In [56]:
np.char.capitalize(arr)

array(['Prince', 'Choudhury'], dtype='<U9')

In [57]:
#Numpy - Mathematical Fuctions.

In [58]:
arr1

array([[1, 3, 8, 8],
       [4, 3, 5, 8],
       [7, 5, 5, 3]])

In [59]:
np.sin(arr1)

array([[ 0.84147098,  0.14112001,  0.98935825,  0.98935825],
       [-0.7568025 ,  0.14112001, -0.95892427,  0.98935825],
       [ 0.6569866 , -0.95892427, -0.95892427,  0.14112001]])

In [60]:
np.cos(arr1)

array([[ 0.54030231, -0.9899925 , -0.14550003, -0.14550003],
       [-0.65364362, -0.9899925 ,  0.28366219, -0.14550003],
       [ 0.75390225,  0.28366219,  0.28366219, -0.9899925 ]])

In [61]:
np.tanh(arr1)

array([[0.76159416, 0.99505475, 0.99999977, 0.99999977],
       [0.9993293 , 0.99505475, 0.9999092 , 0.99999977],
       [0.99999834, 0.9999092 , 0.9999092 , 0.99505475]])

In [62]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.90308999, 0.90308999],
       [0.60205999, 0.47712125, 0.69897   , 0.90308999],
       [0.84509804, 0.69897   , 0.69897   , 0.47712125]])

In [63]:
np.exp(arr1)

array([[2.71828183e+00, 2.00855369e+01, 2.98095799e+03, 2.98095799e+03],
       [5.45981500e+01, 2.00855369e+01, 1.48413159e+02, 2.98095799e+03],
       [1.09663316e+03, 1.48413159e+02, 1.48413159e+02, 2.00855369e+01]])

In [64]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 2.82842712, 2.82842712],
       [2.        , 1.73205081, 2.23606798, 2.82842712],
       [2.64575131, 2.23606798, 2.23606798, 1.73205081]])

In [65]:
np.power(arr1, 2)

array([[ 1,  9, 64, 64],
       [16,  9, 25, 64],
       [49, 25, 25,  9]])

In [66]:
np.mean(arr1)

5.0

In [69]:
np.median(arr1)

5.0

In [70]:
np.std(arr1)

2.23606797749979

In [71]:
np.var(arr1)

5.0

In [ ]:
np.min(arr1)

In [72]:
np.max(arr1)

8

Numpy Part 3

In [73]:
#Sort, Search & Counting Function

In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,5,7,4,36,7,2,3,4,6,64,33])

In [7]:
arr

array([ 1,  2,  5,  7,  4, 36,  7,  2,  3,  4,  6, 64, 33])

In [8]:
np.sort(arr)

array([ 1,  2,  2,  3,  4,  4,  5,  6,  7,  7, 33, 36, 64])

In [9]:
np.searchsorted(arr, 34)

13

In [10]:
arr1 = np.array([534,0,343,0,0,0,43,0,0,0])

In [11]:
arr1

array([534,   0, 343,   0,   0,   0,  43,   0,   0,   0])

In [12]:
np.count_nonzero(arr1)

3

In [13]:
arr

array([ 1,  2,  5,  7,  4, 36,  7,  2,  3,  4,  6, 64, 33])

In [16]:
np.where(arr > 6)   #It will give index

(array([ 3,  5,  6, 11, 12]),)

In [17]:
np.extract(arr > 6, arr)   #It will give greater than 6 data

array([ 7, 36,  7, 64, 33])

In [ ]:
#Numpy - Byte Swapping

In [18]:
arr

array([ 1,  2,  5,  7,  4, 36,  7,  2,  3,  4,  6, 64, 33])

In [19]:
arr.byteswap()

array([  72057594037927936,  144115188075855872,  360287970189639680,
        504403158265495552,  288230376151711744, 2594073385365405696,
        504403158265495552,  144115188075855872,  216172782113783808,
        288230376151711744,  432345564227567616, 4611686018427387904,
       2377900603251621888])

In [20]:
a = np.copy(arr)    #deep copy  : It will not effect original array(Becasue dusre location pe copy banti h)

In [21]:
b = arr.view()      #Shallow copy  : But it will effect original array(Ye kisi dusre location pe copy nahi karta, ye sirf reference add copy karta h)

In [22]:
b

array([ 1,  2,  5,  7,  4, 36,  7,  2,  3,  4,  6, 64, 33])

In [23]:
arr

array([ 1,  2,  5,  7,  4, 36,  7,  2,  3,  4,  6, 64, 33])

In [24]:
b[0] = 67

In [25]:
b       #Shallow copy

array([67,  2,  5,  7,  4, 36,  7,  2,  3,  4,  6, 64, 33])

In [26]:
arr

array([67,  2,  5,  7,  4, 36,  7,  2,  3,  4,  6, 64, 33])

In [27]:
#Numpy - Matrix Library

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5)   #Identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
#Numpy - Linear Algebra

In [35]:
arr1 = np.random.randint([[2,3], [4,5]])

In [36]:
arr2 = np.random.randint([[5,3], [2,5]])

In [37]:
np.dot(arr1, arr2)

array([[0, 4],
       [3, 7]])

In [38]:
arr1@arr2

array([[0, 4],
       [3, 7]])